/* export const URL = "https://127.0.0.1:8000";
export const URL_ADMIN = "/logadmin"
export const URL_REGISTER = "/register";
export const URL_LOGIN = "/login";
export const URL_GENRES_LIST = "/genres-list";
export const URL_PLATFORMS_LIST = "/plateformes-list";
export const URL_PRODUCTS_LIST = "/products-list";
export const URL_SINGLE_PRODUCT = "/single-product"
export const URL_ADD_TO_CART = "/add-to-cart"
export const URL_USER_CART = '/get-cart'
export const URL_UPDATE_CART = '/update-cart'
export const URL_DELETE_CART = '/delete-cart'
export const URL_DELETE_ITEM = '/delete-item'
export const URL_STORAGE_CART = '/get-storage'
export const URL_PAY = '/pay'
export const URL_ORDER = '/order'
export const URL_GET_ORDER = '/get-order'
export const URL_ADD_ADDRESS = '/add-address'
export const URL_GET_ADDRESS = '/get-address' */
export const URL_API_GOUV = "/search/?q=";
/* export const URL_ACCOUNT_ACTIVATION = '/account-activation'
export const URL_ACTIVATION_TOKEN_AGAIN = '/token-activation-again'
export const URL_CHANGE_MAIL = '/change-mail'
export const URL_CHECK_MAIL = '/check-mail'
export const URL_CHANGE_PASSWORD = '/change-password'
export const URL_USER_ORDER = '/order-historic'
export const URL_USER_SINGLE_ORDER = '/single-order-historic'
export const URL_USER_DATA = '/get-user-data'
export const URL_USER_UPLOAD_IMG = '/upload-user-image'
export const URL_USER_AVATAR = '/uploads/images/'
export const URL_USER_CHANGE_PSEUDO = '/change-pseudo'
export const URL_VOTE_TEST = '/vote-test/'
export const URL_USER_TESTS = '/user-tests'
export const URL_GET_TEST = '/get-test/:id';
export const URL_UPDATE_TEST = '/update-test/:id';
export const URL_SUBMIT_TEST = '/submit-test';
export const URL_IMG = '/uploads/images';
export const URL_VG_IMG = '/products/videogames';
export const URL_VG_MAIN_IMG = '/main_img';
export const URL_MAIN_IMG = '/uploads/images/products/videogames/main_img';
export const URL_TRAILER = '/uploads/videos/videogames/trailer';
export const URL_MOVE_TO_WISHLIST = '/move-to-wishlist/:id';
export const URL_ADD_TO_WISHLIST = '/add-to-wishlist/:id';
export const URL_GET_WISHLIST = '/get-wishlist'; */
